openapi: 3.0.0

paths:
  /petsTable:
    get:
      summary: This endpoint returns the list of pets
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:getPets/invocations"
        httpMethod: "POST"
        
  /pet/{pet_id}:
    get:
      summary: This endpoint returns a user given a user id
      parameters:
        - name: pet_id
          in: path
          required: true
          description: pet unique id
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:getPet/invocations"
        httpMethod: "POST"
  
  
  /pets/deleteImage/{petID}:
    put:
      summary: This endpoint returns the list of pets
      parameters:
        - name: petID
          in: path
          required: true
          description: Pet unique id.
          schema:
            type : string
        - name: imageName
          in: query
          required: true
          description: Pet type
          schema:
            type: string
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:deleteImage/invocations"
        httpMethod: "POST"
        
  /pets/{petID}:
    put:
      summary: This endpoint is for updating a pet in db
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Age:
                  type: string
                HealthStatus:
                  type: string
                LocationPet:
                  type: string
                Pictures:
                  type: array
                  properties:
                    items:
                      type: string
                PictureNames:
                  type: array
                  properties:
                    items:
                      type: string
      parameters:
        - name: petID
          in: path
          required: true
          description: Pet unique id.
          schema:
            type : string
        - name: SK
          in: query
          required: true
          description: Pet type
          schema:
            type: string
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:updatePet/invocations"
        httpMethod: "POST"
  
  /pets/solicitAdoption/{adoptID}:
    put:
      summary: This endpoint solicits an adoption (creates a topic with the email and saves it on dynamodb)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                adopted:
                  type: boolean
                email:
                  type: string
      parameters:
        - name: adoptID
          in: path
          required: true
          description: Adoption ID
          schema:
            type : integer
            format: int64
            minimum: 1
        - name: email
          in: query
          required: true
          description: email for the adoption
          schema:
            type: string
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:solicitAdoption/invocations"
        httpMethod: "POST"

# // APPROVAL// #   

  /pets/approveAdoption/{adoptID}:
    put:
      summary: This endpoint aproves an adoption by changing Adopted from false to true
      parameters:
        - name: adoptID
          in: path
          required: true
          description: Adoption ID
          schema:
            type : string
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:approveAdoption/invocations"
        httpMethod: "POST"
  